// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"gateway/internal/config"
	"gateway/internal/controllers"
	"gateway/internal/logger"
	"gateway/internal/service/authservice"
)

// Injectors from wire.go:

func InitApp() *App {
	configConfig := config.New()
	slogLogger := logger.New(configConfig)
	service := authservice.New(configConfig, slogLogger)
	authController := controllers.NewAuthController(service, service)
	app := newApp(configConfig, slogLogger, authController)
	return app
}
