// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.6
// source: templates.proto

package templates

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Templates_CreateLink_FullMethodName              = "/TemplatesService.Templates/CreateLink"
	Templates_UpdateLink_FullMethodName              = "/TemplatesService.Templates/UpdateLink"
	Templates_DeleteLink_FullMethodName              = "/TemplatesService.Templates/DeleteLink"
	Templates_CreateTemplate_FullMethodName          = "/TemplatesService.Templates/CreateTemplate"
	Templates_UpdateTemplate_FullMethodName          = "/TemplatesService.Templates/UpdateTemplate"
	Templates_DeleteTemplate_FullMethodName          = "/TemplatesService.Templates/DeleteTemplate"
	Templates_CreateFeature_FullMethodName           = "/TemplatesService.Templates/CreateFeature"
	Templates_UpdateFeature_FullMethodName           = "/TemplatesService.Templates/UpdateFeature"
	Templates_DeleteFeature_FullMethodName           = "/TemplatesService.Templates/DeleteFeature"
	Templates_GetAllTemplates_FullMethodName         = "/TemplatesService.Templates/GetAllTemplates"
	Templates_GetFeaturesByTemplateId_FullMethodName = "/TemplatesService.Templates/GetFeaturesByTemplateId"
)

// TemplatesClient is the client API for Templates service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TemplatesClient interface {
	CreateLink(ctx context.Context, in *FeatureLinkTemplateStruct, opts ...grpc.CallOption) (*IdStruct, error)
	UpdateLink(ctx context.Context, in *FeatureLinkTemplateStruct, opts ...grpc.CallOption) (*Empty, error)
	DeleteLink(ctx context.Context, in *FeatureLinkTemplateStruct, opts ...grpc.CallOption) (*Empty, error)
	CreateTemplate(ctx context.Context, in *TemplateStruct, opts ...grpc.CallOption) (*IdStruct, error)
	UpdateTemplate(ctx context.Context, in *TemplateStruct, opts ...grpc.CallOption) (*Empty, error)
	DeleteTemplate(ctx context.Context, in *IdStruct, opts ...grpc.CallOption) (*Empty, error)
	CreateFeature(ctx context.Context, in *FeatureStruct, opts ...grpc.CallOption) (*IdStruct, error)
	UpdateFeature(ctx context.Context, in *FeatureStruct, opts ...grpc.CallOption) (*Empty, error)
	DeleteFeature(ctx context.Context, in *IdStruct, opts ...grpc.CallOption) (*Empty, error)
	GetAllTemplates(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TemplatesList, error)
	GetFeaturesByTemplateId(ctx context.Context, in *IdStruct, opts ...grpc.CallOption) (*HibridFeatureLinkTemplateList, error)
}

type templatesClient struct {
	cc grpc.ClientConnInterface
}

func NewTemplatesClient(cc grpc.ClientConnInterface) TemplatesClient {
	return &templatesClient{cc}
}

func (c *templatesClient) CreateLink(ctx context.Context, in *FeatureLinkTemplateStruct, opts ...grpc.CallOption) (*IdStruct, error) {
	out := new(IdStruct)
	err := c.cc.Invoke(ctx, Templates_CreateLink_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templatesClient) UpdateLink(ctx context.Context, in *FeatureLinkTemplateStruct, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, Templates_UpdateLink_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templatesClient) DeleteLink(ctx context.Context, in *FeatureLinkTemplateStruct, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, Templates_DeleteLink_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templatesClient) CreateTemplate(ctx context.Context, in *TemplateStruct, opts ...grpc.CallOption) (*IdStruct, error) {
	out := new(IdStruct)
	err := c.cc.Invoke(ctx, Templates_CreateTemplate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templatesClient) UpdateTemplate(ctx context.Context, in *TemplateStruct, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, Templates_UpdateTemplate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templatesClient) DeleteTemplate(ctx context.Context, in *IdStruct, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, Templates_DeleteTemplate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templatesClient) CreateFeature(ctx context.Context, in *FeatureStruct, opts ...grpc.CallOption) (*IdStruct, error) {
	out := new(IdStruct)
	err := c.cc.Invoke(ctx, Templates_CreateFeature_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templatesClient) UpdateFeature(ctx context.Context, in *FeatureStruct, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, Templates_UpdateFeature_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templatesClient) DeleteFeature(ctx context.Context, in *IdStruct, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, Templates_DeleteFeature_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templatesClient) GetAllTemplates(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TemplatesList, error) {
	out := new(TemplatesList)
	err := c.cc.Invoke(ctx, Templates_GetAllTemplates_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templatesClient) GetFeaturesByTemplateId(ctx context.Context, in *IdStruct, opts ...grpc.CallOption) (*HibridFeatureLinkTemplateList, error) {
	out := new(HibridFeatureLinkTemplateList)
	err := c.cc.Invoke(ctx, Templates_GetFeaturesByTemplateId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemplatesServer is the server API for Templates service.
// All implementations must embed UnimplementedTemplatesServer
// for forward compatibility
type TemplatesServer interface {
	CreateLink(context.Context, *FeatureLinkTemplateStruct) (*IdStruct, error)
	UpdateLink(context.Context, *FeatureLinkTemplateStruct) (*Empty, error)
	DeleteLink(context.Context, *FeatureLinkTemplateStruct) (*Empty, error)
	CreateTemplate(context.Context, *TemplateStruct) (*IdStruct, error)
	UpdateTemplate(context.Context, *TemplateStruct) (*Empty, error)
	DeleteTemplate(context.Context, *IdStruct) (*Empty, error)
	CreateFeature(context.Context, *FeatureStruct) (*IdStruct, error)
	UpdateFeature(context.Context, *FeatureStruct) (*Empty, error)
	DeleteFeature(context.Context, *IdStruct) (*Empty, error)
	GetAllTemplates(context.Context, *Empty) (*TemplatesList, error)
	GetFeaturesByTemplateId(context.Context, *IdStruct) (*HibridFeatureLinkTemplateList, error)
	mustEmbedUnimplementedTemplatesServer()
}

// UnimplementedTemplatesServer must be embedded to have forward compatible implementations.
type UnimplementedTemplatesServer struct {
}

func (UnimplementedTemplatesServer) CreateLink(context.Context, *FeatureLinkTemplateStruct) (*IdStruct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLink not implemented")
}
func (UnimplementedTemplatesServer) UpdateLink(context.Context, *FeatureLinkTemplateStruct) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLink not implemented")
}
func (UnimplementedTemplatesServer) DeleteLink(context.Context, *FeatureLinkTemplateStruct) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLink not implemented")
}
func (UnimplementedTemplatesServer) CreateTemplate(context.Context, *TemplateStruct) (*IdStruct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTemplate not implemented")
}
func (UnimplementedTemplatesServer) UpdateTemplate(context.Context, *TemplateStruct) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTemplate not implemented")
}
func (UnimplementedTemplatesServer) DeleteTemplate(context.Context, *IdStruct) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTemplate not implemented")
}
func (UnimplementedTemplatesServer) CreateFeature(context.Context, *FeatureStruct) (*IdStruct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFeature not implemented")
}
func (UnimplementedTemplatesServer) UpdateFeature(context.Context, *FeatureStruct) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFeature not implemented")
}
func (UnimplementedTemplatesServer) DeleteFeature(context.Context, *IdStruct) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFeature not implemented")
}
func (UnimplementedTemplatesServer) GetAllTemplates(context.Context, *Empty) (*TemplatesList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTemplates not implemented")
}
func (UnimplementedTemplatesServer) GetFeaturesByTemplateId(context.Context, *IdStruct) (*HibridFeatureLinkTemplateList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeaturesByTemplateId not implemented")
}
func (UnimplementedTemplatesServer) mustEmbedUnimplementedTemplatesServer() {}

// UnsafeTemplatesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TemplatesServer will
// result in compilation errors.
type UnsafeTemplatesServer interface {
	mustEmbedUnimplementedTemplatesServer()
}

func RegisterTemplatesServer(s grpc.ServiceRegistrar, srv TemplatesServer) {
	s.RegisterService(&Templates_ServiceDesc, srv)
}

func _Templates_CreateLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeatureLinkTemplateStruct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplatesServer).CreateLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Templates_CreateLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplatesServer).CreateLink(ctx, req.(*FeatureLinkTemplateStruct))
	}
	return interceptor(ctx, in, info, handler)
}

func _Templates_UpdateLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeatureLinkTemplateStruct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplatesServer).UpdateLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Templates_UpdateLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplatesServer).UpdateLink(ctx, req.(*FeatureLinkTemplateStruct))
	}
	return interceptor(ctx, in, info, handler)
}

func _Templates_DeleteLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeatureLinkTemplateStruct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplatesServer).DeleteLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Templates_DeleteLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplatesServer).DeleteLink(ctx, req.(*FeatureLinkTemplateStruct))
	}
	return interceptor(ctx, in, info, handler)
}

func _Templates_CreateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TemplateStruct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplatesServer).CreateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Templates_CreateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplatesServer).CreateTemplate(ctx, req.(*TemplateStruct))
	}
	return interceptor(ctx, in, info, handler)
}

func _Templates_UpdateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TemplateStruct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplatesServer).UpdateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Templates_UpdateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplatesServer).UpdateTemplate(ctx, req.(*TemplateStruct))
	}
	return interceptor(ctx, in, info, handler)
}

func _Templates_DeleteTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdStruct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplatesServer).DeleteTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Templates_DeleteTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplatesServer).DeleteTemplate(ctx, req.(*IdStruct))
	}
	return interceptor(ctx, in, info, handler)
}

func _Templates_CreateFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeatureStruct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplatesServer).CreateFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Templates_CreateFeature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplatesServer).CreateFeature(ctx, req.(*FeatureStruct))
	}
	return interceptor(ctx, in, info, handler)
}

func _Templates_UpdateFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeatureStruct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplatesServer).UpdateFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Templates_UpdateFeature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplatesServer).UpdateFeature(ctx, req.(*FeatureStruct))
	}
	return interceptor(ctx, in, info, handler)
}

func _Templates_DeleteFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdStruct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplatesServer).DeleteFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Templates_DeleteFeature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplatesServer).DeleteFeature(ctx, req.(*IdStruct))
	}
	return interceptor(ctx, in, info, handler)
}

func _Templates_GetAllTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplatesServer).GetAllTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Templates_GetAllTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplatesServer).GetAllTemplates(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Templates_GetFeaturesByTemplateId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdStruct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplatesServer).GetFeaturesByTemplateId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Templates_GetFeaturesByTemplateId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplatesServer).GetFeaturesByTemplateId(ctx, req.(*IdStruct))
	}
	return interceptor(ctx, in, info, handler)
}

// Templates_ServiceDesc is the grpc.ServiceDesc for Templates service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Templates_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TemplatesService.Templates",
	HandlerType: (*TemplatesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLink",
			Handler:    _Templates_CreateLink_Handler,
		},
		{
			MethodName: "UpdateLink",
			Handler:    _Templates_UpdateLink_Handler,
		},
		{
			MethodName: "DeleteLink",
			Handler:    _Templates_DeleteLink_Handler,
		},
		{
			MethodName: "CreateTemplate",
			Handler:    _Templates_CreateTemplate_Handler,
		},
		{
			MethodName: "UpdateTemplate",
			Handler:    _Templates_UpdateTemplate_Handler,
		},
		{
			MethodName: "DeleteTemplate",
			Handler:    _Templates_DeleteTemplate_Handler,
		},
		{
			MethodName: "CreateFeature",
			Handler:    _Templates_CreateFeature_Handler,
		},
		{
			MethodName: "UpdateFeature",
			Handler:    _Templates_UpdateFeature_Handler,
		},
		{
			MethodName: "DeleteFeature",
			Handler:    _Templates_DeleteFeature_Handler,
		},
		{
			MethodName: "GetAllTemplates",
			Handler:    _Templates_GetAllTemplates_Handler,
		},
		{
			MethodName: "GetFeaturesByTemplateId",
			Handler:    _Templates_GetFeaturesByTemplateId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "templates.proto",
}
